# Generated by Django 4.2.2 on 2023-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('family', models.CharField(max_length=150)),
                ('birthday', models.DateField(auto_now_add=True)),
                ('password', models.PositiveIntegerField()),
                ('image', models.ImageField(default='image/default_person_image.jpg', upload_to='users')),
                ('link_facebook', models.TextField(blank=True, null=True)),
                ('link_instagram', models.TextField(blank=True, null=True)),
                ('link_telegram', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
