# Generated by Django 4.2.2 on 2023-06-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_direction'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('added_date', models.DateField(auto_now_add=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.direction')),
                ('members', models.ManyToManyField(blank=True, to='account.profile')),
            ],
        ),
    ]
