# Generated by Django 4.2.2 on 2023-06-10 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('account', '0002_profile_delete_john'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_direction', to='main_app.direction'),
        ),
    ]
