# Generated by Django 4.2.2 on 2023-06-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_task'),
        ('account', '0004_profile_work_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doned_tasks',
            field=models.ManyToManyField(blank=True, related_name='doned_tasks', to='main_app.task'),
        ),
    ]
