# Generated by Django 4.2.2 on 2023-06-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='user_images/'),
        ),
    ]
